In [1]:
print("Hello")
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
import torch
x = torch.rand(5, 3)
print(x)

Hello
TensorFlow version: 2.18.0
tensor([[0.2073, 0.5012, 0.0605],
        [0.5937, 0.6944, 0.8906],
        [0.3342, 0.3823, 0.0044],
        [0.8914, 0.0277, 0.9079],
        [0.6756, 0.1295, 0.6851]])


In [2]:
torch.cuda.is_available()
torch.cuda.device_count()

1

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [5]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [6]:
tensor_back_to_cpu = tensor_on_gpu.cpu()
tensor_back_to_cpu.numpy()

array([1, 2, 3])

In [7]:
torch.manual_seed(0)
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [8]:
torch.manual_seed(0)
random_tensor2 = torch.rand(1, 7)
random_tensor2

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [9]:
random_tensor2 = random_tensor2.T
random_tensor2

tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])

In [10]:
torch.matmul(random_tensor, random_tensor2)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [11]:
torch.cuda.manual_seed(1234)
random_tensor = torch.rand(7, 7)

torch.cuda.manual_seed(1234)
random_tensor2 = torch.rand(1, 7)

random_tensor2 = random_tensor2.T
torch.matmul(random_tensor, random_tensor2)

tensor([[1.1061],
        [0.9868],
        [1.8999],
        [0.7716],
        [1.3174],
        [1.6353],
        [1.7395]])

In [12]:
torch.manual_seed(1234)
first = torch.rand(2, 3)
first

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])

In [13]:
torch.manual_seed(1234)
second = torch.rand(2, 3)
second

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])

In [14]:
first = first.to(device="cuda")
second = second.to(device="cuda")

In [15]:
result = torch.matmul(random_tensor, random_tensor2)
result

tensor([[1.1061],
        [0.9868],
        [1.8999],
        [0.7716],
        [1.3174],
        [1.6353],
        [1.7395]])

In [16]:
torch.min(result)

tensor(0.7716)

In [17]:
torch.max(result)

tensor(1.8999)

In [18]:
torch.manual_seed(7)
ch1 = torch.rand(1, 1, 1 ,10)
ch1

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [19]:
torch.manual_seed(7)
ch2 = torch.rand(10)
ch2

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])